config/routes.rb
Rails.application.routes.draw do

  get '/wikis/public', to: 'wikis#public'

  resources :wikis do
    resources :collaborators
  end

  resources :charges, only: [:new, :create]

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_and_belongs_to_many :wiki_collaborators, :class_name => 'Wiki', :join_table => 'collaborators'

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :premium, -> { where(premium: true) }
  scope :not, ->(id) { where('id != ?', id) }
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_and_belongs_to_many :collaborators, :class_name => 'User', :join_table => 'collaborators'

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :name)}
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    @amount = params[:amount]

    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
   
    # Where the real magic happens
    begin
      charge = Stripe::Charge.create(
        customer: customer.id, # Note -- this is NOT the user_id in the app
        amount: @amount,
        description: "Blocipedia Membership = #{current_user.email}",
        currency: 'usd'
      )

      if current_user.update(premium: true)
        flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
        redirect_to edit_user_registration_path
      else
        flash[:success] = "There was an error upgrading your account. Please contact support!"
        redirect_to edit_user_registration_path
      end

      # Stripe will send back CardErrors, with friendly messages
      # when something goes wrong.
      # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
  end

  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     email: current_user.email,
     description: "Blocipedia Membership - #{current_user.name}",
     amount: 2500 
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def public
    @wikis = Wiki.where('private = ?', false)
  end

  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = current_user.wikis
    @collaborations = current_user.collaborators
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
  end

  # GET /wikis/new
  def new
    @wiki = current_user.wikis.new
  end

  # GET /wikis/1/edit
  def edit
    @users = User.where('id != ?', current_user.id)
    @collaborators = @wiki.collaborators
  end

  # POST /wikis
  # POST /wikis.json
  def create
    @wiki = current_user.wikis.new(wiki_params)

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.friendly.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:name, :body, :user_id, :private, :collaborator_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <!-- The form doesn't pass the amount to the create action, so we have to pass it manually. -->
   <%= hidden_field_tag :amount, @stripe_btn_data[:amount] %>
 
   <h4>Click the button!</h4>
   <script 
      class='stripe-button' 
      src="https://checkout.stripe.com/checkout.js" 
      data-key="<%= @stripe_btn_data[:key] %>" 
      data-amount=<%= @stripe_btn_data[:amount] %> 
      data-name="Blocipedia"
      data-description="One Year Membership"
      data-email="<%= @stripe_btn_data[:email] %>" >
    </script>
 <% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'My Wikis', wikis_path %></li>
  <li><%= link_to 'Wikis', wikis_public_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blocipedia2" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blocipedia2" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div id="epiceditor" class="field">
  </div>
  <%= f.text_area :body, id: "epictextarea", class: 'hide' %>

  <% if @user.premium? && @wiki.user == current_user %>
    <div class="field">
      <%= f.label :private %><br>
      <%= f.check_box :private %>
    </div>
    <% if defined?(edit) && edit %>
      <div class="field">
        <%= f.label :collaborators %><br>
        <% @users.each do |user| %>
          <%= check_box_tag "wiki[collaborator_ids][]",  user.id, @collaborators.include?(user) %><%= user.name || user.email %>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Editing wiki</h1>

<%= render :partial => 'form', :locals => {:edit => true} %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<h1>Listing wikis</h1>

<h2>My wikis</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.name, wiki %></td>
        <td><%= wiki.created_at %></td>
        <td><%= wiki.updated_at %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
        <td><%= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2>Wikis Shared with me</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created By</th>
      <th>Date Created</th>
      <th>Last Updated</th>
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @collaborations.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.name, wiki %></td>
        <td><%= wiki.user.name %></td>
        <td><%= wiki.created_at %></td>
        <td><%= wiki.updated_at %></td>
        <td><%= link_to 'Edit', edit_wiki_path(wiki) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/new.html.erb
<h1>New wiki</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/public.html.erb
<h1>All Public Wikis</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created By</th>
      <th>Date Created</th>
      <th>Last Updated</th>
    </tr>
  </thead>

  <tbody>
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to wiki.name, wiki_path(wiki) %></td>
        <td><%= wiki.user.name %></td>
        <td><%= wiki.created_at %></td>
        <td><%= wiki.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wiki', new_wiki_path %>

app/views/wikis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wiki.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@wiki.body) %>
</p>

<% if @wiki.user == current_user %>
  <%= link_to 'Edit', edit_wiki_path(@wiki) %> |
<% end %>
<%= link_to 'Back', wikis_path %>